146 standardizing embed formats
tomassirio/ListBot pull request #148
Opened 2020-10-24 03:27 UTC by RazCrimson

Fixes #146 and possibly #128 . Take a look and tell me if I need to change something.

2020-10-24 16:55 UTC, rgroves requested changes
Good job, just one thing to patch up and one to remove. Thanks!

2020-10-24 16:55 UTC, rgroves commented on src/commands/list.js
>              const emptyMessage = Util.embedMessage(
There is an issue here that causes the bot to crash when no items are in the list. Looks to be the order of the arguments has been incorrect. In the previous version it wasn't causing the bot to crash though (because it was using the color value where the author should have been, in the message footer). 

Could you patch this up by fixing the order of the arguments passed and maybe making the title look better like you have below by using something like ``List for \`${channelName}\`` is empty!,`

2020-10-24 16:55 UTC, rgroves commented on src/utils/utils.js
>      generateListEmbed(title, color, fields, footer) {
Since `generteListEmbed` is no longer in use please remove this method.

2020-10-24 16:55 UTC, rgroves commented on src/utils/utils.js
>      generateListEmbed(title, color, fields, footer) {
Sorry, this comment should have been on line 13 not line 11.

2020-10-24 23:00 UTC, RazCrimson commented on src/commands/list.js
>              const emptyMessage = Util.embedMessage(
Done.

2020-10-24 23:00 UTC, RazCrimson commented on src/utils/utils.js
>      generateListEmbed(title, color, fields, footer) {
Removed it.

2020-10-25 02:50 UTC, rgroves requested changes
Looking good. Just needs a few more adjustments.

2020-10-25 02:50 UTC, rgroves commented on src/commands/add.js
> +            `Added a item to \`${channel.name}\`'s List`,
Small grammatical issue, make this "Added **an** item..."

2020-10-25 02:50 UTC, rgroves commented on src/commands/demote.js
> +                'Hooray!..'
Grammar issue: remove ".." after "Hooray!"

2020-10-25 02:50 UTC, rgroves commented on src/commands/promote.js
> +            `Added \`${mentionedUser.tag}\` as a admin`,
Grammar: change "as a admin" to "as an admin"

2020-10-25 02:50 UTC, rgroves commented on src/commands/promote.js
> +            'Hooray!..'
Grammar issue: remove ".." after "Hooray!"

2020-10-25 15:32 UTC, rgroves approved these changes

2020-10-25 15:35 UTC, rgroves commented
@RazCrimson great job! Thanks for sticking with this.

2020-10-25 15:40 UTC, merged