Feature/add colour to list
tomassirio/ListBot pull request #149
Opened 2020-10-25 14:19 UTC by anontyro

Notable changes:
  - Added in colour styling using the code block method to most items
 - Poll is not included as it uses emojis and that will not work in code blocks
 - fixed bug with max items in poll, will now max to 5 and allow smaller lists to work as expected
 - fixed an issue when wanting to remove with no number was returning `NaN` but removing the first element changed to safely default to the first item instead
  - Added in node debugging via nodemon --inspect and attach config for it

![Screenshot 2020-10-25 at 22 15 17](https://user-images.githubusercontent.com/18455641/97109693-95329300-170f-11eb-9c33-ee7416f44784.png)
![Screenshot 2020-10-24 at 00 15 09](https://user-images.githubusercontent.com/18455641/97109697-995eb080-170f-11eb-8153-0943a9e58919.png)
![Screenshot 2020-10-25 at 22 17 22](https://user-images.githubusercontent.com/18455641/97109734-dfb40f80-170f-11eb-918e-5c4c4f918b49.png)
![Screenshot 2020-10-25 at 22 17 09](https://user-images.githubusercontent.com/18455641/97109738-e2166980-170f-11eb-9265-46ab19774ea6.png)

2020-10-25 17:18 UTC, rgroves commented
Hey @anontyro as mention in the Discord server a couple days ago, there was one other contributor working along the same lines as you, so there are conflicts in your branch. Please resolve these and then I'll review your changes. Thanks!

2020-10-25 19:40 UTC, RazCrimson commented
Maybe you can move the `Styles` module into `Utils` module as the current `Utils` module only has one embed generator and `MessageStyle` also seems to fit the context of `utils.js`.

2020-10-26 04:57 UTC, rgroves requested changes
I left some notes for the current change set, but in addition conflicts will need resolving as well. Please sync your branch with the current state of the master branch, resolve conflicts, and address the requested changes so that we can move forward with integrating your work into the codebase. Thanks!

I also like the idea from @RazCrimson about incorporating the Styles into the utils, but don't want utils to be a generic catch all, so I think will address this separately by making utils.js more specific (maybe renaming to something like messageUtils.js) and combining both into a message specific utility module.

2020-10-26 04:57 UTC, rgroves commented on .vscode/launch.json
> +}
Let's treat the debugging related changes as a separate issue. Could you please open an feature issue for this?

I think this and the nodemon chnage in `package.json` should be specific to each developer and not necessarily part of the codebase, but would like to discuss it further with you via the Discord server or here in the issue comments.

2020-10-26 04:57 UTC, rgroves commented on package.json
> +        "dev": "cross-env NODE_ENV=development nodemon --inspect --exec babel-node src/index.js",
This should be part of a separate issue and change set if we move forward with it. See comments on the `.vscode/launch.json` file.

2020-10-26 04:57 UTC, rgroves commented on src/commands/poll.js
> +const MAX_ITEMS = 5
Since the changes in this file aren't related to the bot message styling lets treat this as a separate change. Please open an issue for this. Also, I think this might be classified as a general code quality improvement rather than a bug fix. The original version only pulls up to 5 because there are only five elements in the emoji array—slice will adjust the second argument value appropriately if greater than the length of the sequence. Your code does make this explicit though so is an improvement, however it shouldn't be lumped in with the message formatting change issue.

2020-10-26 04:57 UTC, rgroves commented on src/commands/remove.js
> +        let itemIndex = Number(args[0] || 1) - 1
This is an appropriate fix for the index not being provided, but let's not group it with the message formatting changes. Also, this is slated to be fixed currently under Issue #147. Please remove and we'll let the contributor handling that issue fix this up.

2020-10-26 05:06 UTC, anontyro commented
Sure I'll update it with the suggestions

2020-10-26 05:16 UTC, rgroves commented
Thanks! In terms of sorting out the merge conflicts let me know if you need any input there and I'll be glad to provide guidance.

2020-10-26 13:17 UTC, anontyro commented on src/commands/poll.js
> +const MAX_ITEMS = 5
I can make it a separate issue but I would say it is a bug fix considering the max is meant to be 5 as currently if you try and make a poll when your list has more than 5 items it will list all items but they will be `undefined myItem` format, which I would assume is not expected behaviour?

2020-10-26 13:23 UTC, rgroves commented on src/commands/poll.js
> +const MAX_ITEMS = 5
Okay, I didn't realize that behavior was the case. I was just able to recreate, so yes, you're correct definitely a bug fix.

2020-10-26 13:25 UTC, anontyro commented on .vscode/launch.json
> +}
ok removed

2020-10-26 13:26 UTC, anontyro commented on src/commands/poll.js
> +const MAX_ITEMS = 5
removed and will open a separate issue

2020-10-26 13:26 UTC, anontyro commented on src/commands/remove.js
> +        let itemIndex = Number(args[0] || 1) - 1
removed

2020-10-26 14:19 UTC, rgroves requested changes
@anontyro just a few minor adjustments and this will be ready to be merged. Thanks!

2020-10-26 14:19 UTC, rgroves commented on .gitignore
> +.vscode/
Please add a new line at the end of the file.

2020-10-26 14:19 UTC, rgroves commented on src/commands/add.js
> -            message.author,
Would like to keep this change that originated in #148. Passing the author object into `Util.embedMessage` allows us to access any property of the author object (like `.username`, `.displayAvatarURL()`)

2020-10-26 14:19 UTC, rgroves commented on src/utils/utils.js
> -            .setFooter(author.username, author.displayAvatarURL())
Would like to keep this change that originated in #148.

2020-10-26 14:19 UTC, rgroves commented on src/commands/list.js
> -        let channelName = channel.name
Would like to keep this change that originated in #148. Let's preserve the channel name as is.

2020-10-26 14:19 UTC, rgroves commented on src/commands/remove.js
> -            message.author,
Want to keep this as passing the author object. See comments on `utils/messageStyle.js`

2020-10-26 14:19 UTC, rgroves commented on src/commands/random.js
> +        const outputMessage = `< ${randomItem.content} >\nElement was added by : ${randomItem.author}\n---`
Please change to look more like how an item looks when `$list` command is issued.
(i.e. remove "Element was added by : ").

2020-10-27 07:25 UTC, anontyro commented on src/utils/utils.js
> -            .setFooter(author.username, author.displayAvatarURL())
I'll have to check this again but I am quite sure when I had this in before it cause the application to crash, I'll check later for that to be sure

2020-10-27 12:51 UTC, anontyro commented on src/commands/add.js
> -            message.author,
so I do agree if we pass the object it makes it more flexible however currently it is just passing it straight from param to the MessageEmbed which I believe is not setting the correct value in the footer anymore, maybe that should be added in the embedMessage function instead, I can change it back but probably needs looking at separately
![Screenshot 2020-10-27 at 20 49 20](https://user-images.githubusercontent.com/18455641/97303979-174cc400-1896-11eb-8536-1ba8790b7bdc.png) with just author


![Screenshot 2020-10-27 at 20 49 44](https://user-images.githubusercontent.com/18455641/97303947-0ac86b80-1896-11eb-9251-ec608fa105a1.png) what I expect (tag)

2020-10-27 12:54 UTC, anontyro commented on src/commands/add.js
> -            message.author,
actually yes this works better overall think it was just order of things before so probably better will update as well

2020-10-27 12:55 UTC, anontyro commented on src/utils/utils.js
> -            .setFooter(author.username, author.displayAvatarURL())
seems it is fine just some of the changes clash it is fine will revert this as well back to that one

2020-10-27 13:07 UTC, anontyro commented on src/commands/random.js
> +        const outputMessage = `< ${randomItem.content} >\nElement was added by : ${randomItem.author}\n---`
updated and removed

2020-10-27 13:08 UTC, anontyro commented on src/commands/remove.js
> -            message.author,
reverted back to author

2020-10-27 13:08 UTC, anontyro commented on src/commands/list.js
> -        let channelName = channel.name
removed any changes to channel name back inline with previous change

2020-10-27 13:09 UTC, anontyro commented on .gitignore
> +.vscode/
added a line break was a bit weird it didn't like me adding just one seems to be in now however

2020-10-28 00:50 UTC, rgroves requested changes
So close to getting this in, just two more minor adjustments and we'll be there.

2020-10-28 00:50 UTC, rgroves commented on src/utils/utils.js
> +        console.log(author)
Please remove this diagnostic log message.

2020-10-28 00:50 UTC, rgroves commented on src/utils/utils.js
> +            .setFooter(author.username, author.displayAvatarURL)
`displayAvatarURL` is a function that must be called to get the avatar's URL. Please adjust this line to be:
` .setFooter(author.username, author.displayAvatarURL())`

2020-10-29 16:31 UTC, rgroves commented
Hi @anontyro, if you're unavailable to make those last two changes, would you mind checking this option within your pull request screen to give me the ability to add commits to your branch. Then I'll make the changes, commit and push them to your branch and get this merged. Thanks!
![image](https://user-images.githubusercontent.com/891249/97603225-33597e00-19da-11eb-81de-2138785b48d3.png)

2020-10-30 02:13 UTC, merged