Fix #147 empty arguments bug in 'add' and 'remove' commands
tomassirio/ListBot pull request #156
Opened 2020-10-30 19:32 UTC by vitasenka

- Fixed a bug when user calls "add", "multi-add", "remove" and "multi-remove" commands without providing enough arguments.
- Bot now replies with a usage hint if user calls any of the above commands incorrectly.

2020-10-30 19:44 UTC, rgroves commented
Hi @vitasenka would you address the linting issues. You can use `npm run lint` locally to ensure you have no linting issues before performing your final push & PR. If you need input on any of the issues it's reporting please let me know and I'll provide guidance.

2020-10-30 19:56 UTC, rgroves requested changes
Please see review comments and address the linting issues. Also, if you haven't done so, please go through some manual testing of each action to ensure changes result in expected behavior for commands, both with correct usage and incorrect usage.
Thanks!

2020-10-30 19:56 UTC, rgroves commented on src/events/message.js
> +    if (command.hasOwnProperty('min_args') && command.min_args > args.length) {
Use the following instead of `command.hasOwnProperty('min_args')`:
```
Object.prototype.hasOwnProperty.call(command, 'min_args')
```

see: https://eslint.org/docs/rules/no-prototype-builtins

2020-10-31 13:06 UTC, vitasenka commented
@rgroves fixed linting issues and tested commands manually.

2020-10-31 16:16 UTC, rgroves approved these changes
Looks good. 🥳

2020-10-31 16:18 UTC, merged